# Generated by Django 6.0.7 on 2026-07-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
