# Generated by Django 6.0.7 on 2026-07-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_member_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='introduced_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
