# Generated by Django 6.0.7 on 2026-07-08 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bill_introduced_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_candidate_id', models.CharField(max_length=20, unique=True)),
                ('total_receipts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
    ]
